language: go

go:
  - "1.11.x"

services:
  - docker

env:
  global:
    - GOLANGCI_LINT_VERSION=1.15.0
    - GO111MODULE=on
    - GOFLAGS=-mod=vendor

install:
  - curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s -- -b ${TRAVIS_HOME}/bin v${GOLANGCI_LINT_VERSION}

cache:
  directories:
    - ${TRAVIS_HOME}/gometalinter/gometalinter-${GOMETALINTER_VERSION}-linux-amd64

script:
  - golangci-lint run --config .golangci.yml ./...
  - go test -v -race ./...

after_success:
  - docker --version
  - docker build -f Dockerfile.next -t kybernetwork/reserve-data:$TRAVIS_COMMIT .

deploy:
  - provider: script
    script: bash .travis/docker_push
    on:
      all_branches: true
      condition: $TRAVIS_BRANCH =~ ^v3-develop|develop|v3-staging|staging|master$

  - provider: script
    script: bash .travis/awx_job_launch.sh $TRAVIS_BRANCH
    on:
      all_branches: true
