language: go

go:
  - "1.13.x"

services:
  - docker
  - postgresql

addons:
  postgresql: "10"

env:
  global:
    - GOLANGCI_LINT_VERSION=1.21.0
    - GO111MODULE=on
    - GOFLAGS=-mod=vendor

install:
  - curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s -- -b ${TRAVIS_HOME}/bin v${GOLANGCI_LINT_VERSION}
before_install:
  - sudo apt-get update
  - sudo apt-get --yes remove postgresql\*
  - sudo apt-get install -y postgresql-12 postgresql-client-12
  - sudo cp /etc/postgresql/{10,12}/main/pg_hba.conf
  - sudo sed -i 's/port = 5433/port = 5432/' /etc/postgresql/12/main/postgresql.conf
  - sudo service postgresql restart 12
before_script:
  - psql -c "CREATE DATABASE reserve_data;" -U postgres
  - psql -c "CREATE USER reserve_data WITH PASSWORD 'reserve_data';" -U postgres
  - psql -c "ALTER ROLE reserve_data SUPERUSER;" -U postgres

script:
  - golangci-lint run --config .golangci.yml ./...
  - go test -v -race ./...

after_success:
  - docker --version
  - docker build -f Dockerfile.next --label "commit=$TRAVIS_COMMIT" -t kybernetwork/reserve-data:$TRAVIS_COMMIT .
  - docker build -f dockerfiles/Dockerfile.gateway --label "commit=$TRAVIS_COMMIT" -t kybernetwork/reserve-data-gateway:$TRAVIS_COMMIT .
  - docker build -f dockerfiles/Dockerfile.setting --label "commit=$TRAVIS_COMMIT" -t kybernetwork/reserve-data-setting:$TRAVIS_COMMIT .

deploy:
  - provider: script
    script: bash .travis/build_docs.sh
    on:
      all_branches: true

  - provider: script
    script: bash .travis/docker_push
    on:
      all_branches: true
      condition: $TRAVIS_BRANCH =~ ^v3-develop|develop|v3-staging|staging|master$

  - provider: gcs
    access_key_id: $GCS_ACCESS_KEY_ID
    secret_access_key: $GCS_SECRET_KEY_ID
    bucket: dev-reserve-data-docs.knstats.com
    skip_cleanup: true
    local-dir: apidocs/build
    on:
      all_branches: true
      condition: $TRAVIS_BRANCH =~ ^v3-develop$

  - provider: script
    script: bash .travis/awx_job_launch.sh $TRAVIS_BRANCH
    on:
      all_branches: true
