version: '3'

volumes:
  postgres:

services:
  postgres:
    image: 'postgres:11-alpine'
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: reserve_data
      POSTGRES_USER: reserve_data
      POSTGRES_PASSWORD: reserve_data
    ports:
      - '127.0.0.1:5432:5432'
